### ISSUE TITLE
King cannot make a long jump

### ISSUE THREAD

**Issue by zeusk** [zeusk/CS451#16]
![ikkingjump1](https://user-images.githubusercontent.com/1236202/36952189-537510a2-1fda-11e8-8836-68b28e95a8b5.gif)

**Comment by guruanshsingh** [comment]
Not an applicable move for American Checkers. For reference, finalizing the choice for rules to be American Checkers. We are following rules from
http://itsyourturn.com/t_helptopic2030.html
