### ISSUE TITLE
Not detecting available backward U-jump for king

### ISSUE THREAD

**Issue by vivian199664** [zeusk/CS451#17]
This problem can be re-produced with:
"0|1|0|0|0|1|0|1|1|0|1|0|1|0|1|0|0|1|0|1|0|0|0|0|0|0|0|0|0|0|1|0|0|2|0|2|0|0|0|0|2|0|0|0|0|0|2|0|0|0|0|2|0|2|0|2|2|0|3|0|0|0|2|0||"

**Comment by guruanshsingh** [comment]
#21 which has fix for #19 resolves this issue too.
