### ISSUE TITLE
Opponent's name is always "oppo"

### ISSUE THREAD

**Issue by zeusk** [zeusk/CS451#18]
`CheckerBoardWindow.xaml.cs:20 => private string opponentName = "oppo";`

**Comment by zeusk** [comment]
Another aspect of this bug is, the game never waits for someone to join as player2. I can make a move and the game calls sendState even if there is no opponent on the other side yet.

This needs to be fixed in gameClient as well. TBD in next meeting on how to deal with this.

**Comment by vivian199664** [comment]
I fixed this bug, just hasn’t committed yet cuz there’s something else I need to fix. For the waiting part, don’t we wait automatically by receiveState ?

**Comment by zeusk** [comment]
receiveState is called after a move is made and sent to the server.

When there is no opponent, the player shouldn't be allowed to make a move.

**Comment by vivian199664** [comment]
solved by 0ab9601823bb7574a4b63a7f92468fdd9f75084e
