### ISSUE TITLE
King jumps should also be mandatory 

### ISSUE THREAD

**Issue by vivian199664** [zeusk/CS451#19]
@guruanshsingh  Please check out the rule below. Right now when there's a available king jump, other pieces can still move(which is incorrect. That king has to perform that jump)

1.19 **If a jump creates an immediate further capturing opportunity, then the capturing move of the piece (man or king) is continued until all the jumps are completed.** The only exception is that if a man reaches the king-row by means of a capturing move it then becomes a king but may not make any further jumps until their opponent has moved. At the end of the capturing sequence, all captured pieces are removed from the board.

1.20 **All capturing moves are compulsory, whether offered actively or passively.** If there are two or more ways to jump, a player may select any one that they wish, not necessarily that which gains the most pieces. Once started, a multiple jump must be carried through to completion. A man can only be jumped once during a multiple jumping sequence.

**Comment by vivian199664** [comment]
this problem can be reproduced with: 
This problem can be re-produced with:
"0|1|0|0|0|1|0|1|1|0|1|0|1|0|1|0|0|1|0|1|0|0|0|0|0|0|0|0|0|0|1|0|0|2|0|2|0|0|0|0|2|0|0|0|0|0|2|0|0|0|0|2|0|2|0|2|2|0|3|0|0|0|2|0||"

**Comment by zeusk** [comment]
Re-opening this and closing duplicate #27
