### ISSUE TITLE
[GameClient][CheckerBoardWindow] Turn logic

### ISSUE THREAD

**Issue by zeusk** [zeusk/CS451#23]
Since a player can possibly make multiple moves in a single turn,

if player1 calls sendState at every move the player2 client will receive the first state change from receiveState and give control of the game to the player2 while player1 still has serial jumps available and technically it is player1's turn. Now, both clients will accept a move from their respective users.

I've implemented a temporary fix for this, by only sending a state update when either the game ends or when the current player's turn ends (and not after every move)

Requires fix in gameUI logic and gameClient/gameHost

**Comment by vivian199664** [comment]
@zeusk can we have a special signal on sendState when we only update the state but does not allow the other player to receive it?

**Comment by zeusk** [comment]
if we just send the state to server and not let the opponent receive it, that's same as not sending the state at every move but only at the end of turn like in my temporary fix.

**Comment by zeusk** [comment]
I feel we definitely need to track whose turn it is in gameState because I just tried two players over network and both players start game as if it is their move 🤣

**Comment by vivian199664** [comment]
ok but then we can't refresh the board for both players while current player is doing series jumps right?

**Comment by zeusk** [comment]
If we track the player whose turn it is in gameState, we can.

After facing the both players starting game with their turns - we definitely need to track playerTurn in gameState

**Comment by zeusk** [comment]
Fixed in branch feature/netHost

Will close after verifying fix and merge to main.

**Comment by zeusk** [comment]
Fix verified in PR #25
