### ISSUE TITLE
Player's current turn is not ended after a checker becoming a king in a series jump

### ISSUE THREAD

**Issue by vivian199664** [zeusk/CS451#26]
When a regular checker has a series of jump, and one of the jump makes ita king, that player's turn should end right after that checker is crowned, even if there're further jumps available after becoming a king. Right now the back end enables further jump after a piece just get crowned

**Comment by vivian199664** [comment]
before:
01000001
10101010
00020000
00100000
00000001
20200020
00020200
00002020
Is Valid
Move Type4
valid--after:
01000401
10100010
00000000
00100000
00000001
20200020
00020200
00002020
0 5
first click --0 5
2 7
second click-- 0 5 2 7
before:
01000401
10100010
00000000
00100000
00000001
20200020
00020200
00002020
Is Valid
Move Type8
valid--after:
01000001
10100000
00000004
00100000
00000001
20200020
00020200
00002020

**Comment by vivian199664** [comment]
@guruanshsingh So a 2 turned 4 after the first jump, then kept jumping

**Comment by zeusk** [comment]
I think a simple fix to this would be to check for available moves AFTER crowning the unit.

**Comment by zeusk** [comment]
To test this, use the following state:

Mike|Mike|testLocalPlayer|0|1|0|1|0|0|0|1|1|0|1|0|1|0|1|0|0|0|0|0|0|0|0|1|0|0|2|0|0|0|0|0|0|2|0|0|0|0|0|1|2|0|0|0|1|0|0|0|0|0|0|2|0|2|0|2|2|0|2|0|2|0|0|0

Fixed by PR #25
