### ISSUE TITLE
King can move backword and ran over other pieces 

### ISSUE THREAD

**Issue by vivian199664** [zeusk/CS451#33]
This issue can be reproduced by 

OKAY Kurt Schmidt|Mainland|Kurt 
Schmidt|0|4|0|0|0|4|0|0|0|0|0|0|0|0|0|0|0|4|0|0|0|0|0|0|2|0|0|0|0|0|0|0|0|0|0|0|0|0|0|4|0|0|0|0|3|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0
generate a new board
GameClient::sendRecv()+ RECV
GameClient::sendRecv()- OKAY Mainland|Mainland|Kurt Schmidt|0|4|0|0|0|4|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|4|0|0|0|0|0|0|0|0|0|0|0|0|0|0|4|0|0|0|0|3|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0
generate a new board

**Comment by zeusk** [comment]
Verified fixed.
